optimiser:
  name: kfac_jax
  curvature_ema: 0
  initial_damping: 0.006719285745
  learning_rate: 0.01038686419
  momentum: 0.5104738636
  l2_reg: 0
  use_adaptive_learning_rate: False
  use_adaptive_momentum: False
  use_adaptive_damping: False
  inverse_update_period: 1
  min_damping: 0
  num_burnin_steps: 0
batch_size: 800
