optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 2.704186866
  momentum: 0.004083275812
  num_update_steps: 3
  initial_scale_factor: 100
  initial_damping: 1.5245806438202
  scale_factor_multiplier: 1.0
  scale_factor_method: lower_bound
  acceleration_type: shanks
  acceleration_order: 1
  acceleration_kwargs:
    inverse_func: samelson
    modifier: sablonniere
  series_name: damped
# validation_proportion: 0
batch_size: 100
