optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 1.855344179
  momentum: 0.003017969967
  num_update_steps: 6
  initial_scale_factor: 100
  initial_damping: 0.0000000427008295828124
  scale_factor_multiplier: 1.0
  scale_factor_method: lower_bound
  acceleration_type: shanks
  acceleration_order: 0
  acceleration_kwargs:
    inverse_func: samelson
    modifier: sablonniere
  series_name: damped
# validation_proportion: 0
batch_size: 100
