optimiser:
  name: HessianSeriesOptimiser
  num_update_steps: 9
  initial_scale_factor: 100
  scale_factor_multiplier: 1.0
  scale_factor_method: lower_bound
  acceleration_type: shanks
  acceleration_order: 4
  acceleration_kwargs:
    inverse_func: samelson
    modifier: sablonniere
  adaptive_update: True
  hessian_damping_factor: 0.9
  damping_min: 1e-8
  initial_damping: 1.46E-06
  series_name: damped
