optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 1.7868843
  momentum: 0.717107296
  num_update_steps: 18
  initial_scale_factor: 100
  initial_damping: 0.0244334238
  scale_factor_multiplier: 1.0
  scale_factor_method: lower_bound
  acceleration_type: shanks
  acceleration_order: 8
  acceleration_kwargs:
    inverse_func: samelson
    modifier: sablonniere
  series_name: damped
# validation_proportion: 0
