optimiser:
  name: kfac_jax
  curvature_ema: 0.95
  initial_damping: 9.861305085
  l2_reg: 0
  use_adaptive_learning_rate: True
  use_adaptive_momentum: True
  use_adaptive_damping: True
  damping_adaptation_interval: 1
  inverse_update_period: 1
batch_size: 3200
# validation_proportion: 0
