optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 4.533322312
  momentum: 0.02404509942
  num_update_steps: 2
  initial_scale_factor: 100
  initial_damping: 5.42E-06
  scale_factor_multiplier: 1.0
  scale_factor_method: lower_bound
  acceleration_type: shanks
  acceleration_order: 0
  acceleration_kwargs:
    inverse_func: samelson
    modifier: sablonniere
  series_name: damped
# validation_proportion: 0
batch_size: 50
