optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 1.72756612431579
  momentum: 0.8743598609695423
  num_update_steps: 3
  initial_scale_factor: 100
  scale_factor_multiplier: 1.0
  shanks_acceleration_order: 0
  shanks_inverse_function: samelson
  epsilon_modifier: sablonniere
# validation_proportion: 0
