optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 0.5667983434
  momentum: 0.2956017422
  num_update_steps: 17
  initial_scale_factor: 100
  initial_damping: 0.000025117537987944
  scale_factor_multiplier: 1.0
  scale_factor_method: lower_bound
  acceleration_type: shanks
  acceleration_order: 6
  acceleration_kwargs:
    inverse_func: samelson
    modifier: sablonniere
  series_name: damped
# validation_proportion: 0
batch_size: 400
