optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 1.49099565
  momentum: 0.1125512722
  num_update_steps: 20
  initial_scale_factor: 100
  initial_damping: 0.001858395053
  scale_factor_multiplier: 1.0
  scale_factor_method: lower_bound
  acceleration_type: shanks
  acceleration_order: 2
  acceleration_kwargs:
    inverse_func: samelson
    modifier: sablonniere
  series_name: damped
# validation_proportion: 0
batch_size: 1600
