optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 1.579708497
  momentum: 0.2298634872
  num_update_steps: 13
  initial_scale_factor: 100
  initial_damping: 0.064070324996924
  scale_factor_multiplier: 1.0
  scale_factor_method: lower_bound
  acceleration_type: shanks
  acceleration_order: 3
  acceleration_kwargs:
    inverse_func: samelson
    modifier: sablonniere
  series_name: damped
# validation_proportion: 0
