optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 0.733704715249315
  momentum: 0.00869591505308378
  num_update_steps: 19
  initial_scale_factor: 100
  scale_factor_multiplier: 1.0
  scale_factor_method: lower_bound
  acceleration_type: shanks
  acceleration_order: 5
  acceleration_kwargs:
    inverse_func: samelson
    modifier: sablonniere
  series_name: damped
# validation_proportion: 0
