optimiser:
  name: HessianSeriesOptimiser
  num_update_steps: 13
  initial_scale_factor: 100
  scale_factor_multiplier: 1.0
  scale_factor_method: lower_bound
  acceleration_type: shanks
  # acceleration_type: levin
  acceleration_order: 4
  acceleration_kwargs:
    # transform_type: t
    inverse_func: samelson
    modifier: sablonniere
  adaptive_update: True
  hessian_damping_factor: 0.9
  damping_min: 1e-8
  initial_damping: 2.385021016517709e-07
  series_name: damped
batch_size: 1600
