optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 0.1842153355
  num_update_steps: 1
  initial_scale_factor: 100
  scale_factor_multiplier: 1.0
  shanks_acceleration_order: 0
  shanks_inverse_function: samelson
  epsilon_modifier: sablonniere
# validation_proportion: 0
batch_size: 50
