optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 3.683633342
  momentum: 0.3694012534
  num_update_steps: 3
  initial_scale_factor: 100
  scale_factor_multiplier: 1.0
  scale_factor_method: lower_bound
  acceleration_type: shanks
  acceleration_order: 0
  acceleration_kwargs:
    inverse_func: samelson
    modifier: sablonniere
  series_name: damped
# validation_proportion: 0
batch_size: 800
