model:
  name: ResNet18
  num_classes: 100
loss:
  name: cross_entropy_loss
  num_classes: 100
dataset:
  name: CIFAR100
  normalise_inputs: False  # Handled through dataset transform
  normalise_outputs: False
  validation_proportion: 0.1  # 5000/50000

num_epochs: 72
batch_size: 100
forward_pass_extra_kwargs: [is_training]
