optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 1.0
  momentum: 0.5
  num_update_steps: 20
  initial_scale_factor: 100
  initial_damping: 0.0001
  scale_factor_multiplier: 1.0
  scale_factor_method: lower_bound
  acceleration_type: shanks
  acceleration_order: 1
  acceleration_kwargs:
    inverse_func: samelson
    modifier: sablonniere
  series_name: damped
# validation_proportion: 0
