optimiser:
  name: SelectiveNewtonSGD
  learning_rate: 0.01
  momentum: 0
  small_eig_learning_rate: 1.0
  small_eigenvalue_threshold: 1e-8
  eigenvalue_transform_method: abs
# validation_proportion: 0
