model:
  name: MLP
  output_sizes: [50, 1]
  activation: relu
  with_bias: True
loss:
  name: mse_loss
dataset:
  name: UCI_Energy
  normalise_inputs: True
  normalise_outputs: True
  validation_proportion: 0.15

num_epochs: 4000
batch_size: 692 #614
#seed: 5029382
