optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 1.36758688
  momentum: 0.0218563128
  num_update_steps: 4
  initial_scale_factor: 100
  initial_damping: 0.000022126807
  scale_factor_multiplier: 1.0
  scale_factor_method: lower_bound
  acceleration_type: shanks
  acceleration_order: 0
  acceleration_kwargs:
    inverse_func: samelson
    modifier: sablonniere
  series_name: damped
# validation_proportion: 0
batch_size: 200
