optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 1.1015412629854
  momentum: 0.446548147813214
  num_update_steps: 8
  initial_scale_factor: 100
  scale_factor_multiplier: 1.0
  shanks_acceleration_order: 1
  shanks_inverse_function: samelson
  epsilon_modifier: sablonniere
# validation_proportion: 0
batch_size: 200
