optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 0.759674693067854
  num_update_steps: 20
  initial_scale_factor: 100
  scale_factor_multiplier: 1.0
  shanks_acceleration_order: 2
  shanks_inverse_function: samelson
  epsilon_modifier: sablonniere
# validation_proportion: 0
