optimiser:
  name: kfac_jax
  curvature_ema: 0
  initial_damping: 0.2197808501
  learning_rate: 0.08678173597
  momentum: 0.405766089
  l2_reg: 0
  use_adaptive_learning_rate: False
  use_adaptive_momentum: False
  use_adaptive_damping: False
  inverse_update_period: 1
  min_damping: 0
  num_burnin_steps: 0
batch_size: 800
