optimiser:
  name: HessianSeriesOptimiser
  learning_rate: 0.3048871985
  momentum: 0.4275821197
  num_update_steps: 13
  initial_scale_factor: 100
  initial_damping: 0.0577320699989871
  scale_factor_multiplier: 1.0
  scale_factor_method: lower_bound
  acceleration_type: shanks
  acceleration_order: 5
  acceleration_kwargs:
    inverse_func: samelson
    modifier: sablonniere
  series_name: damped
# validation_proportion: 0
batch_size: 400
